import { ProjecTechnology } from "@/interfaces/projects";
import {
  ALACRITY,
  CAREERCUE,
  CHESSMATE,
  MOKO,
  ONEPIECE,
  PATIENVIZ,
  RENEW,
  SHARITY,
} from "../string";

export const projectTechnologies: Record<string, ProjecTechnology> = {
  [SHARITY]: {
    frontend: ["React Native"],
    backend: ["Node.js", "Firebase", "Google Maps API"],
    tools: ["Figma", "GitHub", "VS Code"],
    languages: ["JavaScript"],
    badge: "#D38796",
    badgeTextColor: "white",
    backgroundcolor: "#739AAB",
    textcolor: "white",
  },
  [CAREERCUE]: {
    frontend: ["React"],
    backend: ["Flask", "Cohere Classify API", "SMTP/SSL"],
    tools: ["Figma", "GitHub", "VS Code"],
    languages: ["JavaScript", "CSS", "Python"],
    badge: "#4849B8",
    badgeTextColor: "white",
    backgroundcolor: "#FBDFFD",
    textcolor: "black",
  },
  [ALACRITY]: {
    frontend: ["React"],
    backend: ["Flask", "MySQL"],
    tools: ["Figma", "GitHub", "VS Code"],
    languages: ["JavaScript", "CSS", "Python"],
    badge: "#F4B5DC",
    badgeTextColor: "black",
    backgroundcolor: "#1EAFF8",
    textcolor: "black",
  },
  [CHESSMATE]: {
    frontend: ["Native Android UI"],
    backend: ["Node.js", "MySQL"],
    tools: ["Figma", "GitHub", "Android Studio"],
    languages: ["Java", "C", "Verilog"],
    badge: "#577076",
    badgeTextColor: "white",
    backgroundcolor: "#FFECFB",
    textcolor: "black",
  },
  [MOKO]: {
    frontend: ["React Native"],
    backend: [
      "Node.js",
      "Amazon EC2 server",
      "Google Maps API",
      "S3 (image storage)",
    ],
    tools: ["Figma", "GitHub", "Android Studio"],
    languages: ["JavaScript"],
    badge: "#F58024",
    badgeTextColor: "black",
    backgroundcolor: "#87B676",
    textcolor: "black",
  },
  [PATIENVIZ]: {
    frontend: ["React", "Electron"],
    backend: ["Python Scripts"],
    tools: ["Figma", "GitHub", "VS Code"],
    languages: ["JavaScript", "CSS", "Python"],
    badge: "#52D6C0",
    badgeTextColor: "black",
    backgroundcolor: "#A96385",
    textcolor: "black",
  },
  [RENEW]: {
    frontend: ["React Native", "Redux"],
    backend: ["Node.js", "Firebase", "Google Maps API"],
    tools: ["Figma", "GitHub", "Android Studio"],
    languages: ["TypeScript", "JavaScript", "Java"],
    badge: "#4A6FA5",
    badgeTextColor: "white",
    backgroundcolor: "#839788",
    textcolor: "black",
    //renew: true,
  },
  [ONEPIECE]: {
    frontend: ["React"],
    backend: ["Node.js", "MongoDB", "Express.js"],
    tools: ["Figma", "GitHub", "VS Code"],
    languages: ["JavaScript", "CSS"],
    badge: "#2C2B5B",
    badgeTextColor: "white",
    backgroundcolor: "#AFA384",
    textcolor: "black",
  },
};
