import { ProjecTechnology } from "@/interfaces/projects";
import {
  ALACRITY,
  CAREERCUE,
  CHESSMATE,
  MOKO,
  ONEPIECE,
  PATIENVIZ,
  RENEW,
  SHARITY,
} from "../string";

export const projectTechnologies: Record<string, ProjecTechnology> = {
  [SHARITY]: {
    frontend: ["Figma UI design", "React Native"],
    backend: ["Node.js", "Firebase", "Google Maps API"],
    img: "/images/projects/sharity/sharityTech.svg",
    label: "#D38796",
    textlabel: "white",
    backgroundcolor: "#739AAB",
    textcolor: "white",
  },
  [CAREERCUE]: {
    frontend: ["Figma UI design", "React"],
    backend: ["Flask", "Cohere Classify API", "SMTP/SSL"],
    img: "/images/projects/careercue/tech.svg",
    label: "#4849B8",
    textlabel: "white",
    backgroundcolor: "#FBDFFD",
    textcolor: "black",
  },
  [ALACRITY]: {
    frontend: ["Figma UI design", "React"],
    backend: ["Flask", "MySQL"],
    img: "/images/projects/alacrity/tech.svg",
    label: "#F4B5DC",
    textlabel: "black",
    backgroundcolor: "#1EAFF8",
    textcolor: "black",
  },
  [CHESSMATE]: {
    frontend: ["Figma UI design", "Android Studio"],
    backend: ["Node.js", "MySQL"],
    img: "/images/projects/chessmate/tech.svg",
    label: "#577076",
    textlabel: "white",
    backgroundcolor: "#FFECFB",
    textcolor: "black",
  },
  [MOKO]: {
    frontend: ["Figma UI design", "React Native"],
    backend: [
      "Node.js",
      "Amazon EC2 server",
      "Google Maps API",
      "S3 (image storage)",
    ],
    img: "/images/projects/moko/tech.svg",
    label: "#F58024",
    textlabel: "black",
    backgroundcolor: "#87B676",
    textcolor: "black",
  },
  [PATIENVIZ]: {
    frontend: ["Figma UI design", "React", "Electron"],
    backend: ["Python Scripts"],
    img: "/images/projects/patientviz/tech.svg",
    label: "#52D6C0",
    textlabel: "black",
    backgroundcolor: "#A96385",
    textcolor: "black",
  },
  [RENEW]: {
    frontend: ["Figma UI design", "React Native", "Redux"],
    backend: ["Node.js", "Firebase", "Google Maps API"],
    img: "/images/projects/renew/tech.svg",
    label: "#4A6FA5",
    textlabel: "white",
    backgroundcolor: "#839788",
    textcolor: "black",
    //renew: true,
  },
  [ONEPIECE]: {
    frontend: ["Figma UI design", "React"],
    backend: ["Node.js", "MongoDB", "Express.js"],
    img: "/images/projects/onepiece/tech.svg",
    label: "#2C2B5B",
    textlabel: "white",
    backgroundcolor: "#AFA384",
    textcolor: "black",
  },
};
